export const calculation = {
  title: "This is calculation EN",
  rate: "Rate",
  loanAmount: "Loan amount",
  autoCost: "Cost of the car",
  enterAutoCost: "Enter the value of the car",
  initialPayment: "Initial payment",
  enterInitialPayment: "Enter the initial payment",
  minimumCost: "Minimum {{percentage}} of the cost",
  loanTerm: "Loan term",
  repaymentMethod: "Repayment method",
  annuity: "Annuity",
  equalShares: "Equal shares",
  year: "year",
  period: "years",
  years: "years",
  personalInfo: "Personal info",
  inn: "INN",
  phoneNumber: "Phone number",
  enterIin: "Enter your INN here",
  birthCertificate: "Birth certificate",
  maxSizePdf:
    "The file should be in PDF format and should be no more than 5 mb in size",
  monthlyPayment: "Monthly payment",
  readTheProduct: "Conditions of use of the product",
  getApproved: "Get approved",
  insuranceAndFee: "Insurance and commission",
  term: "Term",
  interestRate: "% rate",
  ANNUITY: 'Аннуитет',
  DIFFERENTIAL: 'Дифференцированный',
  validation: {
    autoCostRequired: "Enter the car cost",
    autoCostMin: "The minimum car amount is {{cost}} ₴",
    autoCostMax: "The maximum car amount is {{cost}} ₴",
    loanCostMin: "The minimum loan amount is {{cost}} ₴",
    loanCostMax: "The maximum loan amount is {{cost}} ₴",
    initialPaymentRequired: "Enter the initial payment",
    loanTermRequired: "Enter the loan term",
    repaymentMethodRequired: "Select a repayment method",
    iinRequired: "Enter the INN",
    iinInvalid: "Enter a valid INN",
    phoneNumberRequired: "Enter the phone number",
    loanAmountMin: "Minimum loan amount is {{amount}} ₴",
    loanAmountMax: "Maximum loan amount is {{amount}} ₴",
    loanAmountRequired: "Enter the loan amount",
  },
  easy: "It's easy!",
  calculate: "Calculate a car loan on favorable conditions",
  realRate: "Real rate",
  bankCommission: "Bank commission",
  totalLoanCosts: "Total loan costs",
  totalCostLoan: "Total cost of the loan",
};
