export const calculation = {
  title: "This is calculation UA",
  rate: "Ставка",
  loanAmount: "Сума позики",
  autoCost: "Вартість автомобіля",
  enterAutoCost: "Введіть вартість авто",
  initialPayment: "Початковий внесок",
  enterInitialPayment: "Введіть початковий внесок",
  minimumCost: "Мінімально {{percentage}} від вартості",
  loanTerm: "Термін позики",
  repaymentMethod: "Метод погашення",
  annuity: "Ануїтет",
  equalShares: "Рівними частками",
  year: "рік",
  period: "року",
  years: "років",
  personalInfo: "Особисті дані",
  inn: "ІІН",
  phoneNumber: "Номер телефону",
  enterIin: "Введіть ІІН тут",
  birthCertificate: "Свідоцтво про народження",
  maxSizePdf: "Файл має бути у форматі PDF і розміром не більше 5 мб",
  monthlyPayment: "Щомісячний платіж",
  readTheProduct: "Умови продукту",
  getApproved: "Отримати схвалення",
  insuranceAndFee: "Страховка і комісія",
  term: "Термін",
  interestRate: "% ставка",
  ANNUITY: 'Аннуитет',
  DIFFERENTIAL: 'Дифференцированный',
  validation: {
    autoCostRequired: "Введіть вартість авто",
    autoCostMin: "Мінімальна сума авто {{cost}} ₴",
    autoCostMax: "Максимальна сума авто {{cost}} ₴",
    loanCostMin: "Мінімальна сума кредиту {{cost}} ₴",
    loanCostMax: "Максимальна сума кредиту {{cost}} ₴",
    initialPaymentRequired: "Введіть початковий внесок",
    loanTermRequired: "Введіть термін кредиту",
    repaymentMethodRequired: "Виберіть метод погашення",
    iinRequired: "Введіть ІПН",
    iinInvalid: "Введіть дійсний ІПН",
    phoneNumberRequired: "Вкажіть номер телефону",
    loanAmountMin: "Мінімальна сума кредиту {{amount}} ₴",
    loanAmountMax: "Максимальна сума кредиту {{amount}} ₴",
    loanAmountRequired: "Введіть суму кредиту",
  },
  easy: "Це легко!",
  calculate: "Розрахуйте автокредит на вигідних умовах",
  realRate: "Реальна ставка",
  bankCommission: "Банківська комісія",
  totalLoanCosts: "Загальні витрати по кредиту",
  totalCostLoan: "Загальна вартість кредиту",
};
