export const calculation = {
  title: "This is calculation RU",
  rate: "Ставка",
  loanAmount: "Сумма займа",
  autoCost: "Стоимость авто",
  enterAutoCost: "Введите стоимость авто",
  initialPayment: "Первоначальный взнос",
  enterInitialPayment: "Введите первоначальный взнос",
  minimumCost: "Минимально {{percentage}} от стоимости",
  loanTerm: "Срок займа",
  repaymentMethod: "Метод погашения",
  annuity: "Аннуитет",
  equalShares: "Равными долями",
  year: "год",
  period: "года",
  years: "лет",
  personalInfo: "Личные данные",
  inn: "ІНН",
  phoneNumber: "Номер телефона",
  enterIin: "Введите ИНН здесь",
  birthCertificate: "Свидетельство о рождении",
  maxSizePdf: "Файл должен быть в формате PDF и размером не более 5 мб",
  monthlyPayment: "Ежемесячный платеж",
  readTheProduct: "Условия продукта",
  getApproved: "Получить одобрение",
  insuranceAndFee: "Страховка и комиссия",
  term: "Срок",
  interestRate: "% ставка",
  ANNUITY: 'Аннуитет',
  DIFFERENTIAL: 'Дифференцированный',
  validation: {
    autoCostRequired: "Введите стоимость авто",
    autoCostMin: "Минимальная сумма авто {{cost}} ₴",
    autoCostMax: "Максимальная сумма авто {{cost}} ₴",
    loanCostMin: "Минимальная сумма кредита {{cost}} ₴",
    loanCostMax: "Максимальная сумма кредита {{cost}} ₴",
    initialPaymentRequired: "Введите начальный взнос",
    loanTermRequired: "Введите срок кредита",
    repaymentMethodRequired: "Выберите метод погашения",
    iinRequired: "Введите ИНН",
    iinInvalid: "Введите валидный ИНН",
    phoneNumberRequired: "Укажите номер телефона",
    loanAmountMin: "Минимальная сумма кредита {{amount}} ₴",
    loanAmountMax: "Максимальная сумма кредита {{amount}} ₴",
    loanAmountRequired: "Введите сумму кредита",
  },
  easy: "Это легко!",
  calculate: "Рассчитайте автокредит на выгодных условиях",
  realRate: "Реальная ставка",
  bankCommission: "Банковская комиссия",
  totalLoanCosts: "Общие затраты по займу",
  totalCostLoan: "Общая стоимость кредита",
};
